---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/conversions":
    get:
      summary: List conversions
      operationId: getConversions
      description: List conversion tasks for user
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 6de8429c-606f-4ba8-9cb9-5762c1ace200
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-15 11:01:19 UTC
                end_time: 
                conversion_job_id: e8cad449-8667-4f88-b90b-2eef3ac254fd
                created_at: 2024-03-15 11:01:19 UTC
                updated_at: 2024-03-15 11:01:19 UTC
                meta:
                  dest_resource_id: 95287e37-92b8-4445-b8e0-4fab8257b218
                  dest_version_id: d5a797c8-85e4-49fb-bffe-fd055024c335
              - id: f1c60da7-a685-445c-aab4-71746d611284
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-15 11:01:19 UTC
                end_time: 
                conversion_job_id: 73666278-b75f-4e3b-b442-51b255645ccc
                created_at: 2024-03-15 11:01:19 UTC
                updated_at: 2024-03-15 11:01:19 UTC
                meta:
                  dest_resource_id: 1f9f36db-85a9-4aa4-85e7-c0e9e9218d0c
                  dest_version_id: 7fe3d88a-429b-4d79-b7db-35ee23ad6f76
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/conversion_task"
  "/api/v1/conversions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show conversion
      operationId: getConversion
      description: Get description of Conversion Task
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 7f23b99b-5b3f-47d2-8ddd-800ec79b6bd4
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-15 11:01:19 UTC
                end_time: 
                conversion_job_id: a95ba7e8-f50c-40df-bbb8-83e3c047de29
                created_at: 2024-03-15 11:01:19 UTC
                updated_at: 2024-03-15 11:01:19 UTC
                meta:
                  dest_resource_id: 8c29f740-66a4-486e-9f2f-2d965133f8fe
                  dest_version_id: ae18f53b-17ab-4c4b-87ce-1989d3417d84
              schema:
                "$ref": "#/components/schemas/conversion_task"
  "/api/v1/conversions/{id}/logs":
    parameters:
    - name: id
      in: path
      description: Conversion Task id
      required: true
      schema:
        type: string
    get:
      summary: logs conversion
      operationId: getConversionLogs
      description: Get logs of Conversion Task (redirect to logs file)
      responses:
        '302':
          description: successful
  "/api/v1/op/convert-anonym":
    post:
      summary: convert_anonym op
      operationId: convertAnonym
      description: Start anonym conversion
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: ff671e2c-bbb1-4735-82bd-7fe20eeae057
                status: inProgress
                progress: '0.0'
                start_time: 2024-03-15 11:01:19 UTC
                end_time: 
                conversion_job_id: ae19813e-528e-4bcb-a30e-bc9b213fc984
                created_at: 2024-03-15 11:01:19 UTC
                updated_at: 2024-03-15 11:01:19 UTC
                meta:
                  dest_resource_id: 01dc4ab4-0c55-4e0e-802c-74b28315d954
                  dest_version_id: 8a1f4e6a-210b-410d-94b2-32853496356e
              schema:
                "$ref": "#/components/schemas/conversion_task"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - input_file
              properties:
                input_file:
                  type: string
                  description: Active Storage signeID
  "/api/v1/resources/{id}/share-options":
    parameters:
    - name: id
      in: path
      description: Resource id
      required: true
      schema:
        type: string
    patch:
      summary: update resource's share_options
      operationId: updateShareOptions
      parameters: []
      responses:
        '204':
          description: successful
        '422':
          description: unprocessable entity
          content:
            application/json:
              example:
                errors:
                  link_password:
                  - is too short (minimum is 8 characters)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link_access:
                  type: string
                  description: Resource view access by link, possible values :none,
                    :view
                  enum:
                  - none
                  - view
                link_password:
                  type: string
                  format: password
  "/api/v1/resources/{id}/share-options/auth-password":
    parameters:
    - name: id
      in: path
      description: Resource id
      required: true
      schema:
        type: string
    post:
      summary: enter password for resource share_option
      operationId: resourceAuthPassword
      parameters: []
      responses:
        '204':
          description: successful
        '422':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                link_password:
                  type: string
                  format: password
components:
  schemas:
    conversion_task:
      type: object
      properties:
        status:
          type: string
          example: finished
        progress:
          type: string
        start_time:
          type: string
          format: date_time
          nullable: true
        end_time:
          type: string
          format: date_time
          nullable: true
        conversion_job_id:
          type: string
          nullable: true
        created_at:
          type: string
          format: date_time
        updated_at:
          type: string
          format: date_time
        meta:
          type: object
          properties:
            dest_resource_id:
              type: string
              nullable: true
            dest_version_id:
              type: string
              nullable: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3050
